Feature/call next ads on period
betajs/betajs-media-components pull request #360
Opened 2023-08-29 12:38 UTC by sambua

2023-08-30 19:55 UTC, ntshcalleia commented on src/dynamics/video_player/player/player.js
> +                    }
```suggestion
                    if (this.get("outstreamoptions.maxadstoshow") === 0) {
                        return promise.asyncError("Limit of showing ads exceeded.", true);
                    }
```

2023-08-30 21:54 UTC, ntshcalleia commented on src/dynamics/video_player/player/player.js
> +                            var isGlobalPromise = typeof this.requestForTheNextAdTagURL().then === "function";
@sambua this is creating an extra call for `requestForTheNextAdTagURL()`. 😬

2023-08-31 13:21 UTC, ntshcalleia requested changes
Hi @sambua, I left a few comments that need to be addressed. Apart from those it looks good to me. 🙂

2023-08-31 13:34 UTC, sambua commented
Hi @ntshcalleia , thanks taking time and for detailed review. I'll make changes and re-push.

2023-09-03 09:17 UTC, sambua commented
Hi @ntshcalleia I've made required changes, please review when you have a time 🙂 .

2023-09-04 18:22 UTC, ntshcalleia approved these changes

2023-09-05 16:09 UTC, sambua commented on src/dynamics/video_player/player/states.js
> +                            }
hi @ntshcalleia , just remember reason why I've left this conditions. When first ad will not be started ads player will be broke. Above condition allow got url from the `nextadtagurls` defined inside `_started` method if `adshassource` not exists, so will put it back.

2023-09-11 14:57 UTC, ntshcalleia commented
Hi @sambua, can you please remove the changes to the `dist` folder or resolve the merge conflicts?

2023-09-12 20:11 UTC, sambua commented
Hi @ntshcalleia I thought I've already did it. Now it's done

2023-09-12 21:39 UTC, merged