Fix/ads user experience
betajs/betajs-media-components pull request #384
Opened 2023-10-04 00:04 UTC by sambua

2023-10-09 17:51 UTC, ntshcalleia commented on src/dynamics/video_player/player/states.js
> +                this.dyn.trigger("resize");
Hi @sambua, we shouldn't manually trigger `resize`, this event should only be triggered by the ResizeObserver.

```suggestion
            }
```

2023-10-09 21:23 UTC, sambua commented
Hi @ntshcalleia, I'm not remember now, but resize trigger fixed something. I'll remove it for now, and if find reason why it was here will let you know.

2023-10-11 18:22 UTC, ntshcalleia commented
> Hi @ntshcalleia, I'm not remember now, but resize trigger fixed something. I'll remove it for now, and if find reason why it was here will let you know.

The changes for ZIG-3145 probably fixes the issue you were having 🙂

2023-10-11 18:50 UTC, ntshcalleia commented
Hi @sambua, can we disable the tooltip for now?
I also noticed that if I mute/unmute the audio during midroll or postroll the changes aren't reflected on the video. Tested on sandbox with this adtagurl: "https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fiu%3D%2F21775744923%2Fexternal%2Fvmap_ad_samples%26sz%3D640x480%26cust_params%3Dsample_ar%253Dpremidpost%26ciu_szs%3D300x250%26gdfp_req%3D1%26ad_rule%3D1%26output%3Dvmap%26unviewed_position_start%3D1%26env%3Dvp%26impl%3Ds%26cmsid%3D496%26vid%3Dshort_onecue%26correlator%3D"

2023-10-11 19:57 UTC, ntshcalleia requested changes
Hi @sambua, can we disable the tooltip for now?
I also noticed that if I mute/unmute the audio during midroll or postroll the changes aren't reflected on the video. Tested on sandbox with this adtagurl: "https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fiu%3D%2F21775744923%2Fexternal%2Fvmap_ad_samples%26sz%3D640x480%26cust_params%3Dsample_ar%253Dpremidpost%26ciu_szs%3D300x250%26gdfp_req%3D1%26ad_rule%3D1%26output%3Dvmap%26unviewed_position_start%3D1%26env%3Dvp%26impl%3Ds%26cmsid%3D496%26vid%3Dshort_onecue%26correlator%3D"

2023-10-12 23:46 UTC, sambua commented
Hi @ntshcalleia I've made some improvements on first detection and for now commented tooltip related addition. Please review when you have a time

To be able test with vmap you can use /static/demos/embed/test-player.html?blk=1&ad=vmap&ap=1 where ad=vmap

2023-10-13 09:46 UTC, ntshcalleia approved these changes

2023-10-13 09:46 UTC, merged